services:
  # Backend API Service
  - type: web
    name: crypto-tracker-api
    env: node
    plan: free
    buildCommand: npm --prefix backend install && npm --prefix backend run build
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: COINMARKETCAP_API_KEY
        sync: false
      - key: DATABASE_PATH
        value: ./data/crypto_tracker.db
    
  # Frontend Static Site
  - type: static
    name: crypto-tracker-frontend
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false 